server:
  port: 8083


base:
  config:
    tidb:
      hostname: 192.168.66.140
      port: 3308


spring:
  application:
    name: blog-article-test
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.141:8848

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.tidb.hostname}:${base.config.tidb.port}/blogs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  type-aliases-package: com.gd.spring.cloud.alibaba.blog.search.domain
  mapper-locations: classpath:mapper/*.xml